export default {
    en:{
        login: `Login`,
        loginTooltip: `Click here to login`,
        all:`All`,
        offer: `Offer`,
        request: `Request`,
        requests:`Requests`,
        offers:`Offers`,
        somethingWentWrong: `Something went wrong while searching, check your network
         connection.`,
         ifTheErrorPersists:`If the error persists then please contact us.`,
         myContactInfo:`My Contact Info`,
         save:`Save`,
         saveTooltip:`Click here to save your info`,
         Name:`Name`,
         contactInfo: `Contact Information`,
         iAgreeToShareMyInfo: `I agree to have this information publicly shared in my posts.`,
         resetPassword:`Reset Password`,
         resetPasswordTooltip:`Click here to reset your password`,
         please: `Please`,
         contactUs: `Contact us`,
         ifStillIssues:`If you are still having issues`, 
         newPassword: `New Password`,
         backToMainPage: `Back to main page`,
         passwordResetSuccess: `Success! Your password has been reset!`,
         resendConfirmationEmail: `Resend Confirmation Email`,
         resend: `Resend`,
         resendConfirmationEmailTooltip: `Click here to get another confirmation Email`,
         email:`Email`,
         password: `Password`,
         confirmPassword: `Confirm Password`,
         confirmationEmailSentSuccess:`Success! You should receive an email 
         from 'no-reply+stitch@mongodb.com' soon. Follow the email to verify
         your account!`,
         reportPost: `Repost Post`,
         report: `Report`,
         reportTooltip: `Click here to report`,
         post:`Post`,
         message:`Message`,
         submitReport:`Submit Report`,
         weAreSorry: `We are sorry for your experience`,
         register: `Register`,
         registerTooltip: `Click here to register`,
         alreadyAccount: `Already have an account?`,
         confirmationEmailProblem: `Problems with confirmation email?`,
         clickHere: `Click here`,
         contact: `Contact`,
         newPost:`New Post`,
         submitPostTooltip: `Click here to submit your post`,
         type: `type`,
         topic:`Topic`,
         topicHelp: `A title for your post`,
         shortDescription: `Short Description`,
         shortDescriptionHelp: `A brief description`,
         description: `Description`,
         descirptionHelp: `A more in=depth description about your post`,
         city:`city`,
         cityHelp: `Where will the learning happen?`,
         addLanguage: `Add Language`,
         addLanguageHelp: `Which languages can be used?`,
         selectIcon: `Select Icon`,
         selectIconHelp: `An icon for your post`,
         peopleCantContact:    `People can't contact you!`,
         provideContactInfo: `Please provide your contact information in User Settings`,
         goUserSettings: `Go to User Settings`,
         openInNewTab: `(Opens in new tab)`,
         forgotPassword:`Forgot your password?`,
         requestNewPassword: `Request new password`,
         requestNewPasswordTooltip: `Click here to request a new password`,
         dontHaveAccount: `Don't have an account?`,
         registerHere: `Register here!`,
         forgotPasswordEmailSuccess: `Success! You should receive an email from 'no-reply+stitch@mongodb.com' soon. Follow the email to reset your password!`,
         delete:`Delete`,
         edit: `Edit`,
         like:`Like`,
         unlike:`Unlike`,
         postDeleteWarning: `Your post will be lost forever`,
         no:`No`,
         yes:`Yes`,
         areYouSure:`Are you sure about that?`,
         feedback:`Give Feedback`,
         about:`About`,
         userOptions:`User Options`,
         contactInfo:`Contact Info`,
         websiteLanguage:`Website Language`,
         onlyMyPosts:`Only My Posts`,
         search:`search`
         
    },
    
    ar:{
        login:` تسجيل خ`,
        loginToolTip: `ع here to login`,
        all:`غ All`,
        offer: `غOffer`,
        request: `عRequest`,
        requests:` عRequests`,
        offers:`عOffers`,
        somethingWentWrong: `عSomething went wrong while searching, check your network
         connection.`,
         ifTheErrorPersists:`عIf the error persists then please contact us.`,
         myContactInfo:`عMy Contact Info`,
         save:`عSave`,
         saveTooltip:`عClick here to save your info`,
         Name:`عName`,
         contactInfo: `عContact Information`,
         iAgreeToShareMyInfo: `عI agree to have this information publicly shared in my posts.`,
         resetPassword:`عReset Password`,
         resetPasswordTooltip:`عClick here to reset your password`,
         please: `عPlease`,
         contactUs: `عContact us`,
         ifStillIssues:`عIf you are still having issues`, 
         newPassword: `عNew Password`,
         backToMainPage: `عBack to main page`,
         passwordResetSuccess: `عSuccess! Your password has been reset!`,
         resendConfirmationEmail: `عResend Confirmation Email`,
         resend: `عResend`,
         resendConfirmationEmailTooltip: `عClick here to get another confirmation Email`,
         email:`عEmail`,
         password: `عPassword`,
         confirmPassword: `عConfirm Password`,
         confirmationEmailSentSuccess:`عSuccess! You should receive an email 
         from 'no-reply+stitch@mongodb.com' soon. Follow the email to verify
         your account!`,
         reportPost: `عRepost Post`,
         report: `عReport`,
         reportTooltip: `عClick here to report`,
         post:`عPost`,
         message:`عMessage`,
         submitReport:`عSubmit Report`,
         weAreSorry: `عWe are sorry for your experience`,
         register: `عRegister`,
         registerTooltip: `عClick here to register`,
         alreadyAccount: `عAlready have an account?`,
         confirmationEmailProblem: `عProblems with confirmation email?`,
         clickHere: `عClick here`,
         contact: `عContact`,
         newPost:`عNew Post`,
         submitPostTooltip: `عClick here to submit your post`,
         type: `عtype`,
         topic:`عTopic`,
         topicHelp: `عA title for your post`,
         shortDescription: `عShort Description`,
         shortDescriptionHelp: `عA brief description`,
         description: `عDescription`,
         descirptionHelp: `عA more in=depth description about your post`,
         city:`عcity`,
         cityHelp: `عWhere will the learning happen?`,
         addLanguage: `عAdd Language`,
         addLanguageHelp: `عWhich languages can be used?`,
         selectIcon: `عSelect Icon`,
         selectIconHelp: `عAn icon for your post`,
         peopleCantContact: `عPeople can't contact you!`,
         provideContactInfo: `عPlease provide your contact information in User Settings`,
         goUserSettings: `عGo to User Settings`,
         openInNewTab: `ع(Opens in new tab)`,
         forgotPassword:`عForgot your password?`,
         requestNewPassword: `عRequest new password`,
         requestNewPasswordTooltip: `عClick here to request a new password`,
         dontHaveAccount: `عDon't have an account?`,
         registerHere: `عRegister here!`,
         forgotPasswordEmailSuccess: `عSuccess! You should receive an email from 'no-reply+stitch@mongodb.com' soon. Follow the email to reset your password!`,
         delete:`غDelete`,
         edit:`غEdit`,
         like:`عlike`,
         unlike:`عunlike`,
         postDeleteWarning: `غYour post will be lost forever`,
         no:`عNo`,
         yes:`عYes`,
         areYouSure:`غAre you sure about that?`,
         feedback:`عGive Feedback`,
         about:`غAbout`,
         userOptions:`غUser Options`,
         contactInfo:`غContact Info`,
         websiteLanguage:`غWebsite Language`,
         onlyMyPosts:`غOnly My Posts`,
         search:`عsearch`

    }
    
}